### ISSUE TITLE
Feature request: alert relabeling

### ISSUE THREAD

**Issue by mcarvalhor** [canonical/cos-configuration-k8s-operator#113]
### Enhancement Proposal

Hi 👋

COS currently uses a model in which prometheus alerts are created and managed by the charm developers.
However, this is a generalist solution that doesn't apply to all teams, all environments or all situations.

Sometimes, we want to add or remove a label depending on the environment stage (production/staging/dev).
Or maybe we want to prioritize business critical environments, and decrease the severity for other environments.

I believe this can be achieved through an "alert relabeling" feature, in which we can override the severity or add other labels for an existing charm alert.

What we expect with this feature is something similar to this:
- We define the existing charm alert name, for example [`PostgresqlTooManyConnections`](https://github.com/canonical/postgresql-operator/blob/c5c916d41d00849da5ae657cba4c97c46cb3caad/src/prometheus_alert_rules/postgresql_rules.yaml#L75)
- We define the matching labels, for example `- juju_model =~ "^stg-.*"`
- We define the labels we want to override, for example: `- severity: info`
- We define the labels we want to add, for example: `- alert_mute_time: weekends` 

So in the end we have a block like this **_for example_**:
```
- alert_relabeling_name: PostgresqlTooManyConnections
  when_matching_labels:
  - juju_model =~ "^stg-.*"   # Models starting with "stg" should be lower severity, and not monitored during weekends.
  then_override_labels:
  - severity: info
  and_add_labels:
  - alert_mute_times: weekends
```

And this should be enough to override label `severity` and add label `alert_mute_times` to all `PostgresqlTooManyConnections` alerts matching `juju_model =~ "^stg-.*"`.
